import gpg key earlier in the action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -41,6 +41,14 @@ runs:
         DOCKER_OPTS: "-v ${{ github.action_path }}/gitconfig:/root/.gitconfig"
       run: "${{ github.workspace }}/contrib/docker/build-bin.sh build"
       shell: sh
+    - name: Import GPG key
+      run: |
+          if [ "${{ inputs.gpg_key }}" = 'none' ]; then
+              echo '### No GPG key defined to sign release, aborting.'
+              exit 1
+          fi
+          echo "${{ inputs.gpg_key }}" | gpg --batch --import -
+      shell: sh
     - name: Sign binaries
       run: |
           for i in build/*; do
@@ -98,11 +106,7 @@ runs:
               'push+refs/tags/v'*) true ;;
               *) echo '### No release tag pushed -- not a release build.'; exit 0 ;;
           esac
-          if [ "${{ inputs.gpg_key }}" = 'none' ]; then
-              echo '### No GPG key defined to sign release, aborting.'
-              exit 1
-          fi
-          echo "${{ inputs.gpg_key }}" | gpg --batch --import -
+
           if [ "${{ github.repository }}" = 'wireleap/client' ]; then
               BUILD_USER="$(id -u)" \
               BUILD_GROUP="$(id -g)" \
